// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {config} from '../models';

export function AddOrUpdateCard(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.Flashcard>;

export function DeleteCardFromDeck(arg1:string,arg2:string):Promise<void>;

export function DeleteDeck(arg1:string):Promise<void>;

export function EscapeHtml(arg1:string):Promise<string>;

export function EscapeHtmlAttribute(arg1:string):Promise<string>;

export function ExportDeckToCSV(arg1:string):Promise<string>;

export function GenerateID():Promise<string>;

export function GetCardContent(arg1:string,arg2:string):Promise<string>;

export function GetCardSRSData(arg1:string):Promise<models.CardData>;

export function GetCards(arg1:Array<string>,arg2:number):Promise<Array<models.Flashcard>>;

export function GetCardsFromDeck(arg1:string):Promise<Array<models.Flashcard>>;

export function GetDecks():Promise<Record<string, models.Deck>>;

export function GetFutureReviewCards():Promise<Array<models.Flashcard>>;

export function GetReviewCards():Promise<Array<models.Flashcard>>;

export function GetReviewCardsForDeck(arg1:string):Promise<Array<models.Flashcard>>;

export function ImportDeckFromCSV(arg1:string,arg2:string):Promise<void>;

export function LoadConfig():Promise<config.Config>;

export function NewDeck(arg1:string):Promise<models.Deck>;

export function SaveConfig(arg1:string):Promise<void>;

export function ToHTML(arg1:string):Promise<string>;

export function UpdateConfigFromJSON(arg1:string):Promise<void>;

export function UpdateSRSData(arg1:string,arg2:string,arg3:models.ReviewConfidence):Promise<void>;
