// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {config} from '../models';

export function AddOrUpdateCard(arg1:string,arg2:string,arg3:string,arg4:string):Promise<storage.Flashcard>;

export function GetCardContent(arg1:string,arg2:string):Promise<string>;

export function GetDecks():Promise<{[key: string]: storage.Deck}>;

export function GetReviewCards():Promise<Array<storage.Flashcard>>;

export function LoadConfig():Promise<config.Config>;

export function NewDeck(arg1:string):Promise<storage.Deck>;

export function PlayAudioFile(arg1:string):Promise<void>;

export function SaveConfig(arg1:string):Promise<void>;

export function Speak(arg1:string,arg2:string):Promise<void>;

export function UpdateConfigFromJSON(arg1:string):Promise<void>;

export function UpdateSRSData(arg1:string,arg2:string,arg3:number):Promise<void>;
