// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddOrUpdateCard(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddOrUpdateCard'](arg1, arg2, arg3, arg4);
}

export function GetCardContent(arg1, arg2) {
  return window['go']['main']['App']['GetCardContent'](arg1, arg2);
}

export function GetDecks() {
  return window['go']['main']['App']['GetDecks']();
}

export function GetReviewCards() {
  return window['go']['main']['App']['GetReviewCards']();
}

export function NewDeck(arg1) {
  return window['go']['main']['App']['NewDeck'](arg1);
}

export function UpdateSRSData() {
  return window['go']['main']['App']['UpdateSRSData']();
}
