// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Load():Promise<main.ConfigResult>;

export function Save(arg1:string):Promise<void>;
