// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportDeck(arg1:string):Promise<string>;

export function ImportDeck(arg1:string,arg2:string):Promise<void>;
